[package]
name = "deser-cbor"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
version = "0.8.0"
edition = "2021"
description = "CBOR support for deser"
repository = "https://github.com/mitsuhiko/deser"
keywords = ["serialization", "deserialization", "cbor"]
readme = "README.md"
license = "Apache-2.0"
documentation = "https://docs.rs/deser-cbor"

[dependencies]
deser = { version = "0.8.0", path = "../deser", default-features = false }

[dev-dependencies]
deser = { version = "0.8.0", path = "../deser", features = ["derive"] }
