[package]
name = "deser-json"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
version = "0.8.0"
edition.workspace = true
rust-version.workspace = true
description = "JSON support for deser"
repository = "https://github.com/mitsuhiko/deser"
keywords = ["serialization", "deserialization"]
readme = "README.md"
license = "Apache-2.0"
documentation = "https://docs.rs/deser-json"
autotests = false

[features]
default = ["io"]
# reading and writing values from and to streams (with `deser::io`)
io = ["deser/io"]
speedups = ["itoa", "ryu", "simdutf8"]

[dependencies]
deser = { version = "0.8.0", path = "../deser", default-features = false }
itoa = { version = "1.0.1", optional = true }
ryu = { version = "1.0.9", optional = true }
simdutf8 = { version = "0.1.5", optional = true }

[dev-dependencies]
deser = { version = "0.8.0", path = "../deser", features = ["derive"] }
deser-location = { version = "0.8.0", path = "../deser-location" }

[[test]]
name = "integration"
path = "tests/integration.rs"
