[package]
name = "located"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-json = { path = "../../deser-json" }
deser-location = { path = "../../deser-location" }
deser-path = { path = "../../deser-path" }

[[bin]]
name = "located"
path = "src/main.rs"
test = false
doc = false
