[package]
name = "plist"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-plist = { path = "../../deser-plist" }

[[bin]]
name = "plist"
path = "src/main.rs"
test = false
doc = false
