[workspace]
members = [
  "deser",
  "deser-debug",
  "deser-derive",
  "deser-cbor",
  "deser-json",
  "deser-location",
  "deser-path",
  "deser-yaml",
  "deser-toml",
  "examples/crate-path",
  "examples/derive",
  "examples/enums",
  "examples/json",
  "examples/located",
  "examples/manual-struct",
]
resolver = "2"
