[package]
name = "renames"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-toml = { path = "../../deser-toml" }

[[bin]]
name = "renames"
path = "src/main.rs"
test = false
doc = false
