[package]
name = "config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-env = { path = "../../deser-env" }
deser-path = { path = "../../deser-path" }
deser-toml = { path = "../../deser-toml" }
deser-urlencoded = { path = "../../deser-urlencoded" }
deser-validate = { path = "../../deser-validate" }

[[bin]]
name = "config"
path = "src/main.rs"
test = false
doc = false
