[package]
name = "deser-path"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
version = "0.8.0"
edition.workspace = true
rust-version.workspace = true
description = "Path wrapping extension for deser"
repository = "https://github.com/mitsuhiko/deser"
keywords = ["serialization", "deserialization"]
readme = "README.md"
license = "Apache-2.0"
documentation = "https://docs.rs/deser-path"
autotests = false

[dependencies]
deser = { version = "0.8.0", path = "../deser", default-features = false }

[dev-dependencies]
deser = { version = "0.8.0", path = "../deser", features = ["derive"] }
deser-json = { path = "../deser-json" }

[[test]]
name = "integration"
path = "tests/integration.rs"
