[package]
name = "bytes"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-cbor = { path = "../../deser-cbor" }
deser-json = { path = "../../deser-json" }
deser-toml = { path = "../../deser-toml" }

[[bin]]
name = "bytes"
path = "src/main.rs"
test = false
