[package]
name = "manual-struct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-debug = { path = "../../deser-debug" }
