[package]
name = "manual-struct"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deser = { path = "../../deser" }
deser-debug = { path = "../../deser-debug" }

[[bin]]
name = "manual-struct"
path = "src/main.rs"
test = false
doc = false
