//! The core of [deser](https://docs.rs/deser).
//!
//! This crate is an implementation detail of deser, use the
//! [`deser`](https://docs.rs/deser) crate instead which re-exports
//! everything in here together with the derive macros.  The crates of the
//! data formats depend on this crate so that they can be compiled without
//! waiting for the derive macros.
#![cfg_attr(docsrs, feature(doc_cfg))]

#[macro_use]
mod macros;
mod event;

pub mod adapters;
pub mod de;
mod error;
pub mod ext;
pub mod hints;
#[cfg(feature = "io")]
pub mod io;
pub mod ser;

mod extensions;
mod foreign_impls;
mod position;
mod state;
mod std_impls;
mod streamed;

pub use self::error::{Error, ErrorAttachment, ErrorKind};
pub use self::event::{Atom, Bytes, ContainerShape, Event, Order};
pub use self::extensions::EventData;
pub use self::position::Position;
pub use self::state::{ErrorContext, State};
pub use self::streamed::Streamed;

// common re-exports

#[doc(no_inline)]
pub use self::{de::Deserialize, ser::Serialize};

#[cfg(feature = "derive")]
pub mod derive;

// Helpers for writing formats (float formatting, small copies).  Not
// public API.
#[doc(hidden)]
#[path = "format.rs"]
pub mod __format;

// Everything the code generated by the derive refers to.  Not public API.
// Standard library items are re-exported so that the generated code does
// not depend on what the names refer to where the derive is used.
#[cfg(feature = "derive")]
#[doc(hidden)]
pub mod __derive {
    pub use std::borrow::Cow;
    pub use std::boxed::Box;
    pub use std::convert::Into;
    pub use std::default::Default;
    pub use std::marker::{PhantomData, Send, Sync};
    pub use std::mem::replace;
    pub use std::option::Option::{self, None, Some};
    pub use std::primitive::{str, u8};
    pub use std::result::Result::{Err, Ok};
    pub use std::string::String;
    pub use std::unreachable;
    pub use std::vec::Vec;
    pub type Result<T> = std::result::Result<T, super::Error>;
    pub type StrCow<'a> = Cow<'a, str>;

    pub use crate::adapters::ser_impls::SerializeAsRef;
    pub use crate::adapters::{DerivedDeserialize, DerivedSerialize};
    pub use crate::de::atoms::{
        atom_into, atom_into_handle, borrowed_atom_into, borrowed_atom_into_handle, field_update,
        unit_struct,
    };
    pub use crate::de::duplicates::{duplicate_field, mark_seen};
    pub use crate::de::enums::{
        AdjacentlyTaggedSink, BoxedVariant, EnumKey, ExternallyTaggedSink, IgnoredContent,
        IgnoredVariant, InternallyTaggedSink, OtherVariant, Tag, UntaggedTry, Variant,
        VariantMaker, Variants, atom_sink, lookup_atom, unit_variant, unknown_variant_atom,
        untagged_atom, untagged_borrowed_atom, untagged_fallback, untagged_handle,
    };
    pub use crate::de::fields::{FieldKeySink, NextField, StructUpdateSink, UpdateFields};
    pub use crate::de::mapped::mapped;
    pub use crate::de::recording::RecordBuf;
    pub use crate::de::unknown::{unclaimed_keys, unknown_field, wants_unknown_fields};
    pub use crate::de::update::{UpdateTarget, replace_with};
    pub use crate::de::validate::{
        Validator, invalid_value, validate_slot, validated, validated_with,
    };
    pub use crate::error::unknown_variant;
    pub use crate::ser::begin::{
        Begin, FIELDS_END, IndexedSeq, IndexedSeqEmitter, IndexedStruct, IndexedStructEmitter,
        PlainSink, StructField,
    };
    pub use crate::ser::enums::{
        EntrySer, FieldSer, FieldsSer, FlatFieldsSer, SeqSer, TaggedNewtype, skipped_variant,
    };
    pub use crate::ser::flatten::FlattenedStruct;

    /// Returns the errors a struct collected together with the fields that
    /// are missing.
    ///
    /// `missing` tells for the required fields (with the indexes and names
    /// given) if they have no value.  Fields that were seen but have no
    /// value failed, they are not missing.
    #[cold]
    #[inline(never)]
    pub fn collected_errors(
        errors: &mut crate::de::CollectedErrors,
        seen: &[u64],
        missing: &[bool],
        indexes: &[usize],
        names: &[&str],
        state: &super::State,
    ) -> super::Error {
        for ((missing, index), name) in missing.iter().zip(indexes).zip(names) {
            if *missing && !crate::de::duplicates::is_seen(seen, *index) {
                errors.push(new_missing_field_error(name, state), state);
            }
        }
        match errors.take() {
            Some(err) => err,
            None => unreachable!(),
        }
    }

    /// Creates the error for the first missing field.
    ///
    /// If errors are collected, the error holds all missing fields.
    #[cold]
    pub fn missing_field(missing: &[bool], names: &[&str], state: &super::State) -> super::Error {
        if state.collects_errors() {
            let errors = missing
                .iter()
                .zip(names)
                .filter(|(missing, _)| **missing)
                .map(|(_, name)| state.attach_error_context(new_missing_field_error(name, state)));
            if let Some(err) = super::Error::from_errors(errors) {
                return err;
            }
        }
        let index = missing.iter().position(|x| *x).unwrap_or_default();
        new_missing_field_error(names[index], state)
    }

    #[cold]
    pub fn new_missing_field_error(name: &str, state: &super::State) -> super::Error {
        if state.discards_errors {
            return crate::error::discarded_error(super::ErrorKind::MissingField);
        }
        super::Error::new(
            super::ErrorKind::MissingField,
            format!("missing field `{}`", name),
        )
    }
}
