//! Support for open enums (`#[deser::open_enum]`).
//!
//! An open enum is a trait whose implementations are its variants.  The
//! trait objects (`Box<dyn Trait>` and `Arc<dyn Trait>`) are serialized and
//! deserialized like enums whose variants are the types that implement the
//! trait with `#[deser::variant]`, which can be in any crate.
//!
//! Serializing only needs the value: the variant knows its name.  To
//! deserialize, the variants are looked up in the [`OpenEnums`] registry
//! of the context, where they are registered explicitly.  The macros only
//! generate the descriptions of the variants and short forwarding
//! functions, everything else is here (generic over the trait object).
use alloc::borrow::Cow;
use alloc::boxed::Box;
use alloc::collections::BTreeMap;
use alloc::string::ToString;
use alloc::sync::Arc;
use alloc::vec::Vec;
use core::any::{Any, TypeId};
use core::fmt;
use core::marker::PhantomData;

use crate::State;
use crate::Text;
use crate::de::enums::{
    AdjacentlyTaggedSink, ArenaVariant, EnumKey, ExternallyTaggedSink, InternallyTaggedSink, Tag,
    VariantBuilder, VariantNames, Variants,
};
use crate::de::mapped::mapped;
use crate::de::{Deserialize, OwnedSink, Sink, SinkHandle};
use crate::error::{Error, ErrorKind};
use crate::event::{Atom, ContainerShape};
use crate::ser::enums::{EntrySer, FieldsSer, TaggedNewtype};
use crate::ser::{
    Describe, Emit, Serialize, SerializeHandle, SerializeRef, Variant, VariantKind, VariantRepr,
};

/// A trait whose trait objects are open enums.
///
/// This is implemented for the trait object of a trait marked with
/// [`#[deser::open_enum]`](../deser/attr.open_enum.html), the
/// implementations of the trait marked with `#[deser::variant]` are its
/// variants (see [`OpenVariant`]).  Its members are not public API.
pub trait OpenEnum: Send + Sync + 'static {
    /// The configuration of the open enum.
    #[doc(hidden)]
    const INFO: &'static OpenEnumInfo;

    /// Returns the variant of a value.
    #[doc(hidden)]
    fn __private_variant(value: &Self) -> VariantValue<'_, Self>;
}

/// A type that is a variant of the open enum `O` (a trait object).
///
/// This is implemented by `#[deser::variant]` for the types that implement
/// the trait.  Variants are registered in an [`OpenEnums`] registry to be
/// deserialized.  Its members are not public API.
pub trait OpenVariant<O: ?Sized + OpenEnum>: 'static {
    /// The description of the variant.
    #[doc(hidden)]
    const ENTRY: &'static VariantEntry<O>;
}

/// Creates the builder of a variant.
///
/// The marker argument implies `'de: 'a` so that functions which are
/// generic over both lifetimes can be converted to this type.
#[doc(hidden)]
pub type MakeVariant<O> =
    for<'a, 'de> fn(&mut State, PhantomData<&'a &'de ()>) -> ArenaVariant<'a, 'de, Box<O>>;

/// The number of name styles of [`VariantEntry::styled`].
const STYLES: usize = 8;

/// The description of a variant of an open enum (generated by
/// `#[deser::variant]`).
#[doc(hidden)]
pub struct VariantEntry<O: ?Sized + 'static> {
    /// The name of the type in all styles of `rename_all`.
    ///
    /// The first one is the name of the type unchanged (the default), the
    /// order of the others is the one of `RenameAll` in deser-derive.
    pub styled: &'static [&'static str; STYLES],
    /// The name given with `rename`.
    pub rename: Option<Tag<'static>>,
    /// The aliases given with `alias`.
    pub aliases: &'static [Tag<'static>],
    /// Returns the name of the type in Rust (for errors).
    pub type_name: fn() -> &'static str,
    /// Creates the builder of the variant.
    pub make: MakeVariant<O>,
}

/// How the variants of an open enum are represented.
#[doc(hidden)]
#[derive(Clone, Copy)]
pub enum OpenRepr {
    /// Externally tagged (a map with the name as key).
    External,
    /// Internally tagged (the name in a field of the content).
    Internal {
        /// The key of the tag.
        tag: EnumKey,
    },
    /// Adjacently tagged (the name and the content in two fields).
    Adjacent {
        /// The key of the tag.
        tag: EnumKey,
        /// The key of the content.
        content: EnumKey,
        /// If keys other than the tag and the content are errors.
        deny_unknown_fields: bool,
    },
}

/// The configuration of an open enum (from `#[deser::open_enum]`).
#[doc(hidden)]
pub struct OpenEnumInfo {
    /// The name of the trait (for errors and descriptions).
    pub name: &'static str,
    /// How the variants are represented.
    pub repr: OpenRepr,
    /// The style of the names of the variants (an index into
    /// [`VariantEntry::styled`]).
    pub rename_all: usize,
    /// The styles in which the names of variants are accepted as well
    /// (`alias_all`).
    pub alias_all: &'static [usize],
}

/// The variant of a value and the value to serialize as its content.
///
/// This is returned by the hidden method that `#[deser::open_enum]` adds to
/// the trait (and `#[deser::variant]` implements).
#[doc(hidden)]
pub struct VariantValue<'a, O: ?Sized + 'static> {
    entry: &'static VariantEntry<O>,
    content: SerializeRef<'a>,
}

impl<'a, O: ?Sized + 'static> VariantValue<'a, O> {
    /// Creates the variant of a value.
    #[inline]
    pub fn new<T: Serialize>(entry: &'static VariantEntry<O>, value: &'a T) -> VariantValue<'a, O> {
        VariantValue {
            entry,
            content: SerializeRef::new(value),
        }
    }
}

impl<O: ?Sized + OpenEnum> VariantEntry<O> {
    /// Returns the name of the variant.
    #[inline]
    fn name(&'static self) -> Tag<'static> {
        match self.rename {
            Some(name) => name,
            None => Tag::Str(self.styled[O::INFO.rename_all]),
        }
    }

    /// Returns a handle to the name of the variant.
    ///
    /// The name is borrowed from the static entry.
    #[inline]
    fn name_handle(&'static self) -> SerializeHandle<'static> {
        match self.rename {
            Some(Tag::Str(ref name)) => SerializeHandle::to(name),
            Some(ref name) => SerializeHandle::to(name),
            None => SerializeHandle::to(&self.styled[O::INFO.rename_all]),
        }
    }

    /// Returns the name of the variant as string (if it is one).
    #[inline]
    fn name_str(&'static self) -> Option<&'static str> {
        match self.name() {
            Tag::Str(name) => Some(name),
            _ => None,
        }
    }

    /// Returns the names the variant is deserialized from.
    fn tags(&'static self) -> Vec<Tag<'static>> {
        let name = self.name();
        let mut tags = Vec::from([name]);
        let mut push = |tag: Tag<'static>| {
            if !tags.contains(&tag) {
                tags.push(tag);
            }
        };
        for &alias in self.aliases {
            push(alias);
        }
        // the names in the styles of `alias_all`
        for &style in O::INFO.alias_all {
            push(Tag::Str(self.styled[style]));
        }
        tags
    }

    /// Returns the name for messages.
    fn display_name(&self) -> Cow<'static, str> {
        match self.rename {
            Some(tag) => tag_display(tag),
            None => Cow::Borrowed(self.styled[O::INFO.rename_all]),
        }
    }
}

/// Returns a tag for messages.
fn tag_display(tag: Tag<'static>) -> Cow<'static, str> {
    match tag {
        Tag::Str(name) => Cow::Borrowed(name),
        Tag::U64(value) => Cow::Owned(value.to_string()),
        Tag::I64(value) => Cow::Owned(value.to_string()),
        Tag::Bool(value) => Cow::Borrowed(if value { "true" } else { "false" }),
    }
}

/// The registry of the variants of open enums.
///
/// Open enums (see [`#[deser::open_enum]`](../deser/attr.open_enum.html))
/// are deserialized with the variants registered here, the registry is
/// given to the deserialization in the [`Context`](crate::Context).  A
/// registry holds the variants of any number of open enums.  Types are
/// variants of an open enum if they implement the trait with
/// `#[deser::variant]`, which [`register`](Self::register) checks:
///
/// ```
/// use deser::{Context, Deserialize, OpenEnums, Serialize};
///
/// #[deser::open_enum(tag = "type")]
/// pub trait Shape: Send + Sync {}
///
/// #[derive(Serialize, Deserialize)]
/// pub struct Circle {
///     radius: u32,
/// }
///
/// #[deser::variant]
/// impl Shape for Circle {}
///
/// let mut variants = OpenEnums::new();
/// variants.register::<dyn Shape, Circle>().unwrap();
/// let context = Context::with(variants);
/// ```
///
/// Libraries that provide variants usually provide a function that
/// registers them.  Only the registered variants can be deserialized,
/// which is also a way to restrict what input can create.  Serializing
/// does not need the registry.
#[derive(Default)]
pub struct OpenEnums {
    enums: BTreeMap<TypeId, Registered>,
}

/// The variants of an open enum.
struct Registered {
    // the name of the open enum
    name: &'static str,
    // the names of the variants (sorted, for errors and `Debug`)
    names: Vec<Cow<'static, str>>,
    // the `Table<O>` of the open enum
    table: Box<dyn Any + Send + Sync>,
}

/// The variants of an open enum by their tags.
struct Table<O: ?Sized + 'static> {
    // the variants with the type they belong to (sorted by tag)
    tags: Vec<(Tag<'static>, TypeId, &'static VariantEntry<O>)>,
}

impl OpenEnums {
    /// Creates an empty registry.
    pub fn new() -> OpenEnums {
        OpenEnums::default()
    }

    /// Registers the type `T` as variant of the open enum `O`.
    ///
    /// `O` is the trait object (`dyn Trait`).  Registering a type again
    /// does nothing.  Fails if the name of the variant (or one of its
    /// aliases) is the one of another variant.
    pub fn register<O: ?Sized + OpenEnum, T: OpenVariant<O>>(
        &mut self,
    ) -> Result<&mut OpenEnums, DuplicateVariant> {
        let entry = T::ENTRY;
        let ty = TypeId::of::<T>();
        let registered = self
            .enums
            .entry(TypeId::of::<O>())
            .or_insert_with(|| Registered {
                name: O::INFO.name,
                names: Vec::new(),
                table: Box::new(Table::<O> { tags: Vec::new() }),
            });
        let table = registered
            .table
            .downcast_mut::<Table<O>>()
            .expect("the table of an open enum has the type of the open enum");
        if table.tags.iter().any(|&(_, other, _)| other == ty) {
            return Ok(self);
        }
        let tags = entry.tags();
        for tag in &tags {
            if let Ok(index) = table.tags.binary_search_by(|(other, _, _)| other.cmp(tag)) {
                return Err(DuplicateVariant {
                    open_enum: O::INFO.name,
                    name: tag_display(*tag),
                    types: [(table.tags[index].2.type_name)(), (entry.type_name)()],
                });
            }
        }
        for tag in tags {
            let index = table
                .tags
                .binary_search_by(|(other, _, _)| other.cmp(&tag))
                .unwrap_err();
            table.tags.insert(index, (tag, ty, entry));
        }
        let name = entry.display_name();
        let index = registered.names.binary_search(&name).unwrap_or_else(|x| x);
        registered.names.insert(index, name);
        Ok(self)
    }

    /// Returns the variants of an open enum.
    #[inline]
    fn get<O: ?Sized + OpenEnum>(&self) -> Option<&Registered> {
        self.enums.get(&TypeId::of::<O>())
    }

    /// Looks up the variant of an open enum by tag.
    #[inline]
    fn lookup<O: ?Sized + OpenEnum>(&self, tag: Tag<'_>) -> Option<&'static VariantEntry<O>> {
        let table = self.get::<O>()?.table.downcast_ref::<Table<O>>()?;
        let index = table
            .tags
            .binary_search_by(|(other, _, _)| other.cmp(&tag))
            .ok()?;
        Some(table.tags[index].2)
    }
}

impl fmt::Debug for OpenEnums {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_map()
            .entries(
                self.enums
                    .values()
                    .map(|registered| (registered.name, &registered.names)),
            )
            .finish()
    }
}

/// The error for a variant whose name is the one of another variant (see
/// [`OpenEnums::register`]).
#[derive(Debug, Clone)]
pub struct DuplicateVariant {
    open_enum: &'static str,
    name: Cow<'static, str>,
    types: [&'static str; 2],
}

impl DuplicateVariant {
    /// Returns the name of the open enum.
    pub fn open_enum(&self) -> &str {
        self.open_enum
    }

    /// Returns the name that is used twice.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Returns the names of the types of the variant that was registered
    /// before and the one that was registered now.
    pub fn types(&self) -> [&str; 2] {
        self.types
    }
}

impl fmt::Display for DuplicateVariant {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "duplicate variant `{}` of {}: `{}` and `{}`",
            self.name, self.open_enum, self.types[0], self.types[1]
        )
    }
}

impl core::error::Error for DuplicateVariant {}

impl Serialize for Tag<'_> {
    fn serialize<'a>(value: &'a Self, _state: &mut State) -> Result<Emit<'a>, Error> {
        Ok(Emit::Atom(match *value {
            Tag::Str(name) => Atom::Str(Text::borrowed(name)),
            Tag::U64(value) => Atom::U64(value),
            Tag::I64(value) => Atom::I64(value),
            Tag::Bool(value) => Atom::Bool(value),
        }))
    }
}

/// Returns how a variant is described.
fn variant_repr(repr: OpenRepr) -> VariantRepr<'static> {
    match repr {
        OpenRepr::External => VariantRepr::External,
        OpenRepr::Internal { tag } => VariantRepr::Internal { tag: tag.name },
        OpenRepr::Adjacent { tag, content, .. } => VariantRepr::Adjacent {
            tag: tag.name,
            content: content.name,
        },
    }
}

/// Serializes the trait object of an open enum.
pub fn serialize<'a, O: ?Sized + OpenEnum>(
    value: &'a O,
    state: &mut State,
) -> Result<Emit<'a>, Error> {
    let VariantValue { entry, content } = O::__private_variant(value);
    Ok(match O::INFO.repr {
        OpenRepr::External => match entry.name_str() {
            Some(name) => {
                FieldsSer(Vec::from([(name, SerializeHandle::from(content))])).into_emit(state)
            }
            None => {
                EntrySer::new(entry.name_handle(), SerializeHandle::from(content)).into_emit(state)
            }
        },
        OpenRepr::Internal { tag } => TaggedNewtype::new(tag.name, entry.name_handle(), content)
            .allow_unit()
            .into_emit(state),
        OpenRepr::Adjacent {
            tag,
            content: content_key,
            ..
        } => FieldsSer(Vec::from([
            (tag.name, entry.name_handle()),
            (content_key.name, SerializeHandle::from(content)),
        ]))
        .into_emit(state),
    })
}

/// Describes the trait object of an open enum.
pub fn describe<O: ?Sized + OpenEnum>(value: &O, d: &mut dyn Describe) {
    let VariantValue { entry, content } = O::__private_variant(value);
    let name = entry.display_name();
    let repr = O::INFO.repr;
    d.variant(&Variant::new(
        O::INFO.name,
        &name,
        VariantKind::Newtype,
        variant_repr(repr),
    ));
    // the fields of the content are merged with the tag, like for newtype
    // variants of internally tagged enums
    if let OpenRepr::Internal { .. } = repr {
        content.describe(d);
    }
}

/// Returns the shape of the trait object of an open enum.
pub fn container_shape<O: ?Sized + OpenEnum>() -> ContainerShape {
    match O::INFO.repr {
        OpenRepr::External => ContainerShape::with_len(1),
        OpenRepr::Internal { .. } => ContainerShape::new(),
        OpenRepr::Adjacent { .. } => ContainerShape::with_len(2),
    }
}

/// Looks up the variant of an open enum by its tag.
fn lookup<'a, 'de: 'a, O: ?Sized + OpenEnum>(
    tag: Tag<'_>,
    state: &mut State,
) -> Option<ArenaVariant<'a, 'de, Box<O>>> {
    let entry = match state.get::<OpenEnums>() {
        Some(registry) if registry.get::<O>().is_some() => registry.lookup::<O>(tag)?,
        _ => {
            return Some(ArenaVariant::new(
                Unregistered::<Box<O>> {
                    name: O::INFO.name,
                    _marker: PhantomData,
                },
                state,
            ));
        }
    };
    Some((entry.make)(state, PhantomData))
}

/// Returns the names of the variants of an open enum for errors.
fn names<O: ?Sized + OpenEnum>(state: &State) -> Vec<&str> {
    match state
        .get::<OpenEnums>()
        .and_then(|registry| registry.get::<O>())
    {
        Some(registered) => registered.names.iter().map(|name| &**name).collect(),
        None => Vec::new(),
    }
}

/// No variant is a unit variant (the variants are given as a tag receive a
/// null as content).
fn no_unit<E>(_tag: Tag<'_>) -> Option<E> {
    None
}

/// Deserializes the trait object of an open enum in a box.
pub fn deserialize_box<'out, 'de, O: ?Sized + OpenEnum>(
    out: &'out mut Option<Box<O>>,
    state: &mut State,
) -> SinkHandle<'out, 'de> {
    let variants = Variants {
        lookup: lookup::<O>,
        other: None,
        default: None,
        names: VariantNames::Dynamic(names::<O>),
    };
    let name = O::INFO.name;
    match O::INFO.repr {
        OpenRepr::External => ExternallyTaggedSink::handle(out, name, variants, no_unit, state),
        OpenRepr::Internal { tag } => InternallyTaggedSink::handle(out, tag, name, variants, state),
        OpenRepr::Adjacent {
            tag,
            content,
            deny_unknown_fields,
        } => AdjacentlyTaggedSink::handle(
            out,
            tag,
            content,
            name,
            variants,
            deny_unknown_fields,
            state,
        ),
    }
}

/// Deserializes the trait object of an open enum in an `Arc`.
pub fn deserialize_arc<'out, 'de, O: ?Sized + OpenEnum>(
    out: &'out mut Option<Arc<O>>,
    state: &mut State,
) -> SinkHandle<'out, 'de>
where
    Box<O>: Deserialize<'de>,
{
    mapped(
        out,
        OwnedSink::<Box<O>>::deserialize(state),
        |value| Ok(Arc::from(value)),
        state,
    )
}

/// Creates the builder of a variant (the type `V` converted into `E`).
///
/// Internally tagged variants receive the fields besides the tag as map.
/// Types that do not accept maps (like unit structs) are deserialized from
/// null if there are no other fields, so that they are given by the tag
/// alone (which is how they are serialized).
pub fn variant<'a, 'de: 'a, V, E>(
    convert: fn(V) -> E,
    state: &mut State,
) -> ArenaVariant<'a, 'de, E>
where
    V: Deserialize<'de> + 'a,
    E: 'a,
{
    ArenaVariant::new(
        ValueBuilder {
            sink: OwnedSink::deserialize(state),
            convert,
            map_error: None,
        },
        state,
    )
}

/// The builder of a variant (see [`variant`]).
struct ValueBuilder<'de, V, E> {
    sink: OwnedSink<'de, V>,
    convert: fn(V) -> E,
    // the error of the sink for the map of an internally tagged variant,
    // which is only reported if the map has fields
    map_error: Option<Error>,
}

impl<'de, V: Deserialize<'de>, E> ValueBuilder<'de, V, E> {
    /// Returns the error for a field of a map that the value rejected.
    #[inline]
    fn check_map(&mut self) -> Result<(), Error> {
        match self.map_error.take() {
            Some(err) => Err(err),
            None => Ok(()),
        }
    }
}

impl<'de, V: Deserialize<'de>, E> VariantBuilder<'de, E> for ValueBuilder<'de, V, E> {
    fn sink(&mut self) -> &mut dyn Sink<'de> {
        self
    }

    fn build(&mut self) -> Option<E> {
        self.sink.take().map(self.convert)
    }
}

impl<'de, V: Deserialize<'de>, E> Sink<'de> for ValueBuilder<'de, V, E> {
    fn atom(&mut self, atom: Atom, state: &mut State) -> Result<(), Error> {
        self.sink.get_mut().atom(atom, state)
    }

    fn borrowed_atom(&mut self, atom: Atom<'de>, state: &mut State) -> Result<(), Error> {
        self.sink.get_mut().borrowed_atom(atom, state)
    }

    fn map(&mut self, state: &mut State) -> Result<(), Error> {
        if let Err(err) = self.sink.get_mut().map(state) {
            self.map_error = Some(err);
        }
        Ok(())
    }

    fn seq(&mut self, state: &mut State) -> Result<(), Error> {
        self.sink.get_mut().seq(state)
    }

    fn next_key(&mut self, state: &mut State) -> Result<SinkHandle<'_, 'de>, Error> {
        self.check_map()?;
        self.sink.get_mut().next_key(state)
    }

    fn next_value(&mut self, state: &mut State) -> Result<SinkHandle<'_, 'de>, Error> {
        self.check_map()?;
        self.sink.get_mut().next_value(state)
    }

    fn __private_key_atom(&mut self, atom: Atom, state: &mut State) -> Result<(), Error> {
        self.check_map()?;
        self.sink.get_mut().__private_key_atom(atom, state)
    }

    fn __private_value_atom(&mut self, atom: Atom, state: &mut State) -> Result<(), Error> {
        self.check_map()?;
        self.sink.get_mut().__private_value_atom(atom, state)
    }

    fn __private_borrowed_key_atom(
        &mut self,
        atom: Atom<'de>,
        state: &mut State,
    ) -> Result<(), Error> {
        self.check_map()?;
        self.sink.get_mut().__private_borrowed_key_atom(atom, state)
    }

    fn __private_borrowed_value_atom(
        &mut self,
        atom: Atom<'de>,
        state: &mut State,
    ) -> Result<(), Error> {
        self.check_map()?;
        self.sink
            .get_mut()
            .__private_borrowed_value_atom(atom, state)
    }

    fn value_for_key(
        &mut self,
        key: &str,
        state: &mut State,
    ) -> Result<Option<SinkHandle<'_, 'de>>, Error> {
        self.check_map()?;
        self.sink.get_mut().value_for_key(key, state)
    }

    fn recover(&mut self, err: Error, state: &mut State) -> Result<(), Error> {
        self.sink.get_mut().recover(err, state)
    }

    fn finish(&mut self, state: &mut State) -> Result<(), Error> {
        if let Some(err) = self.map_error.take() {
            // an empty map, the value is given by the tag alone
            let sink = self.sink.get_mut();
            if sink.atom(Atom::Null, state).is_err() {
                return Err(err);
            }
        }
        self.sink.get_mut().finish(state)
    }

    fn expecting(&self) -> Cow<'_, str> {
        self.sink.get().expecting()
    }
}

/// The builder of the variants of an open enum which has no registered
/// variants: the registry is missing from the context.
struct Unregistered<E> {
    name: &'static str,
    _marker: PhantomData<fn() -> E>,
}

impl<E> Unregistered<E> {
    fn error(&self) -> Error {
        Error::new(
            ErrorKind::UnsupportedType,
            alloc::format!(
                "no variants of {} are registered (register them in a deser::OpenEnums \
                 that is given in the context)",
                self.name
            ),
        )
    }
}

impl<'de, E> VariantBuilder<'de, E> for Unregistered<E> {
    fn sink(&mut self) -> &mut dyn Sink<'de> {
        self
    }

    fn build(&mut self) -> Option<E> {
        None
    }
}

impl<'de, E> Sink<'de> for Unregistered<E> {
    fn atom(&mut self, _atom: Atom, _state: &mut State) -> Result<(), Error> {
        Err(self.error())
    }

    fn map(&mut self, _state: &mut State) -> Result<(), Error> {
        Err(self.error())
    }

    fn seq(&mut self, _state: &mut State) -> Result<(), Error> {
        Err(self.error())
    }

    fn finish(&mut self, _state: &mut State) -> Result<(), Error> {
        Err(self.error())
    }
}
