//! <div align="center">
//!  <img src="https://raw.githubusercontent.com/mitsuhiko/deser/main/artwork/logo.svg" width="250" height="250">
//!  <p><strong>deser: an experimental serialization and deserialization library for Rust</strong></p>
//! </div>
//!
//! Deser is an experimental serialization system for Rust.  It wants to explore
//! the possibilities of serialization and deserialization of structural formats
//! such as JSON or msgpack.  It intentionally does not desire to support non
//! self describing formats such as bincode.
//!
//! With the `derive` feature it supports deriving structures that can be
//! serialized and derserialized automatically:
//!
#![cfg_attr(
    feature = "derive",
    doc = r#"
```rust
use deser::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
#[deser(rename_all = "camelCase")]
pub struct Account {
    id: usize,
    account_holder: String,
    is_deactivated: bool,
}
```
"#
)]
//!
//! To serialize or deserialize this a data format implementation is needed.  At the moment
//! the following formats are supported:
//!
//! * [`deser-json`](https://docs.rs/deser-json): implements JSON serialization and
//!   deserialization.
//! * [`deser-cbor`](https://docs.rs/deser-cbor): implements CBOR serialization and
//!   deserialization.
//! * [`deser-toml`](https://docs.rs/deser-toml): implements TOML serialization and
//!   deserialization.
//! * [`deser-yaml`](https://docs.rs/deser-yaml): implements YAML serialization and
//!   deserialization.
//!
//! The data formats have a deserializer (which deserializes values from a
//! slice) and a serializer (which serializes values into a buffer).  Values
//! can also be read from and written to streams (such as files or sockets),
//! see [`io`][io-module].
//!
//! The data model can be extended with types that are not native to it.  For
//! more information see [`ext`].
//!
//! How individual values are serialized and deserialized can be customized
//! with adapters, which compose with containers.  For more information see
//! [`adapters`].  Types which only implement serde's traits can be used with
//! the adapters of [`deser-serde`](https://docs.rs/deser-serde).
//!
//! # Features
//!
//! * `derive` turns on basic derive support for [`Serialize`] and [`Deserialize`].  For more
//!   information see [`derive`][derive-module].
//! * `jiff`, `chrono`, `time`, `uuid`, `rust_decimal`, `bigdecimal` and `num-bigint`
//!   implement [`Serialize`] and [`Deserialize`] for the types of these crates.  They
//!   are serialized as [well-known types](crate::ext#well-known-types) which data
//!   formats can support natively.
//! * `bytes-encoding` adds more encodings for bytes (such as base32) to
//!   [`adapters::bytes`].
//! * `io` (enabled by default) adds [`io`][io-module] to read values from and
//!   write values to streams.
//!
#![cfg_attr(feature = "derive", doc = "[derive-module]: crate::derive")]
#![cfg_attr(feature = "io", doc = "[io-module]: crate::io")]
#![cfg_attr(
    not(feature = "io"),
    doc = "[io-module]: https://docs.rs/deser/latest/deser/io/"
)]
#![cfg_attr(
    not(feature = "derive"),
    doc = "[derive-module]: https://docs.rs/deser/latest/deser/derive/"
)]
#![cfg_attr(docsrs, feature(doc_cfg))]

#[macro_use]
mod macros;
mod event;

pub mod adapters;
pub mod de;
mod error;
pub mod ext;
pub mod hints;
#[cfg(feature = "io")]
pub mod io;
pub mod ser;

mod extensions;
mod position;
mod state;
mod std_impls;
mod streamed;

#[cfg(doctest)]
mod soundness;

#[cfg(all(doctest, feature = "derive"))]
mod derive_errors;

pub use self::error::{Error, ErrorAttachment, ErrorKind};
pub use self::event::{Atom, Bytes, ContainerShape, Event, Order};
pub use self::extensions::EventData;
pub use self::position::Position;
pub use self::state::{ErrorContext, State};
pub use self::streamed::Streamed;

// common re-exports

#[doc(no_inline)]
pub use self::{de::Deserialize, ser::Serialize};

#[cfg(feature = "derive")]
#[doc(no_inline)]
pub use deser_derive::{Deserialize, Serialize};

#[cfg(feature = "derive")]
pub mod derive;

// Everything the code generated by the derive refers to.  Not public API.
// Standard library items are re-exported so that the generated code does
// not depend on what the names refer to where the derive is used.
#[cfg(feature = "derive")]
#[doc(hidden)]
pub mod __derive {
    pub use std::borrow::Cow;
    pub use std::boxed::Box;
    pub use std::convert::Into;
    pub use std::default::Default;
    pub use std::marker::{PhantomData, Send, Sync};
    pub use std::mem::replace;
    pub use std::option::Option::{self, None, Some};
    pub use std::primitive::{str, u8};
    pub use std::result::Result::{Err, Ok};
    pub use std::string::String;
    pub use std::vec::Vec;
    pub type Result<T> = std::result::Result<T, super::Error>;
    pub type StrCow<'a> = Cow<'a, str>;

    pub use crate::de::atoms::{
        atom_into, atom_into_handle, borrowed_atom_into, borrowed_atom_into_handle,
    };
    pub use crate::de::enums::{
        AdjacentlyTaggedSink, BoxedVariant, ExternallyTaggedSink, IgnoredContent, IgnoredVariant,
        InternallyTaggedSink, OtherVariant, Variant, VariantMaker, Variants, untagged_handle,
    };
    pub use crate::ser::begin::{Begin, IndexedStruct, IndexedStructEmitter, StructField};
    pub use crate::ser::enums::{EntrySer, FieldsSer, SeqSer, TaggedNewtype};
    pub use crate::ser::flatten::FlattenedStruct;

    #[cold]
    pub fn new_missing_field_error(name: &str) -> super::Error {
        super::Error::new(
            super::ErrorKind::MissingField,
            format!("Missing field '{}'", name),
        )
    }
}
