[package]
name = "query-strings"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-path = { path = "../../deser-path" }
deser-urlencoded = { path = "../../deser-urlencoded" }

[[bin]]
name = "query-strings"
path = "src/main.rs"
test = false
doc = false
