[package]
name = "derive"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-debug = { path = "../../deser-debug" }

[[bin]]
name = "derive"
path = "src/main.rs"
test = false
