[package]
name = "json-numbers"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive", "jiff"] }
deser-json = { path = "../../deser-json" }
jiff = "0.2.14"

[[bin]]
name = "json-numbers"
path = "src/main.rs"
test = false
