[package]
name = "tokio-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-json = { path = "../../deser-json" }
deser-tokio = { path = "../../deser-tokio", features = ["codec"] }
futures-util = { version = "0.3.30", default-features = false, features = ["sink"] }
tokio = { version = "1.38", features = ["macros", "net", "rt-multi-thread"] }
tokio-util = { version = "0.7.11", features = ["codec"] }

[[bin]]
name = "tokio-server"
path = "src/main.rs"
test = false
doc = false
