#!/usr/bin/env bash
# Generates the pickle test data in deser-pickle/tests/data.
#
# There is no shared test suite for the pickle format, CPython is the
# reference.  scripts/pickle/generate.py collects inputs (the cases in
# scripts/pickle/cases.py and the bytes literals of the pickle tests of
# CPython) and records how the unpickler of the pinned Python version reads
# them, without importing or calling anything.  See generate.py for the
# format of the results.
#
# Requires docker.  To update, change the pinned versions below and re-run
# the script.
set -euo pipefail

PYTHON_IMAGE=python:3.14.3-slim
CPYTHON_REPO=python/cpython
CPYTHON_COMMIT=323c59a5e348347be2ce2b7ea55fcb30bf68b2d3 # v3.14.3

HERE="$(cd "$(dirname "$0")" && pwd)"
DATA="$HERE/../deser-pickle/tests/data"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if ! command -v docker > /dev/null; then
  echo "docker is required" >&2
  exit 1
fi

mkdir -p "$TMP/cpython" "$TMP/out"
curl -fsSL "https://github.com/$CPYTHON_REPO/archive/$CPYTHON_COMMIT.tar.gz" \
  | tar -xz -C "$TMP/cpython" --strip-components=1 \
    "cpython-$CPYTHON_COMMIT/LICENSE" "cpython-$CPYTHON_COMMIT/Lib/test"

# the hash seed is fixed for the order of sets
docker run --rm \
  -e PYTHONHASHSEED=0 \
  -v "$HERE/pickle:/scripts:ro" \
  -v "$TMP/cpython:/cpython:ro" \
  -v "$TMP/out:/out" \
  "$PYTHON_IMAGE" \
  python /scripts/generate.py /cpython /out/cases.json

OUT="$DATA/pickle"
rm -rf "$OUT"
mkdir -p "$OUT"
cp "$TMP/out/cases.json" "$OUT/cases.json"
cp "$TMP/cpython/LICENSE" "$OUT/LICENSE"
cat > "$OUT/SOURCE" <<EOS
Generated by scripts/update-pickle-test-data.sh with $PYTHON_IMAGE.

Inputs are taken from scripts/pickle/cases.py and from
https://github.com/$CPYTHON_REPO commit $CPYTHON_COMMIT
(bytes literals of Lib/test/pickletester.py, test_pickle.py and
test_pickletools.py), LICENSE is the license of CPython.  The expected
results are the output of CPython's unpickler with the globals replaced by
stand-ins (nothing is imported or called).
EOS

echo "Updated $DATA"
