#!/usr/bin/env bash
# Generates the PHP serialize test data in deser-php/tests/data.
#
# There is no shared test suite for PHP's serialize format, PHP itself is
# the reference.  scripts/php-serialize/generate.php collects inputs (the
# cases in scripts/php-serialize/cases.php, serialized looking strings of
# the .phpt tests of php-src and its unserialize fuzzer corpus) and
# records how unserialize() of the pinned PHP version reads them.  See
# generate.php for the format of the results.
#
# Requires docker.  To update, change the pinned versions below and re-run
# the script.
set -euo pipefail

PHP_IMAGE=php:8.5.11-cli
PHP_SRC_REPO=php/php-src
PHP_SRC_COMMIT=fab508fe1ca8e89d5ae16bf1cac31d07576462ee

HERE="$(cd "$(dirname "$0")" && pwd)"
DATA="$HERE/../deser-php/tests/data"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if ! command -v docker > /dev/null; then
  echo "docker is required" >&2
  exit 1
fi

mkdir -p "$TMP/php-src" "$TMP/out"
curl -fsSL "https://github.com/$PHP_SRC_REPO/archive/$PHP_SRC_COMMIT.tar.gz" \
  | tar -xz -C "$TMP/php-src" --strip-components=1

docker run --rm \
  -v "$HERE/php-serialize:/scripts:ro" \
  -v "$TMP/php-src:/php-src:ro" \
  -v "$TMP/out:/out" \
  "$PHP_IMAGE" \
  php /scripts/generate.php /php-src /scripts/cases.php /out/cases.json

OUT="$DATA/php-serialize"
rm -rf "$OUT"
mkdir -p "$OUT"
cp "$TMP/out/cases.json" "$OUT/cases.json"
cp "$TMP/php-src/LICENSE" "$OUT/LICENSE"
cat > "$OUT/SOURCE" <<EOS
Generated by scripts/update-php-test-data.sh with $PHP_IMAGE.

Inputs are taken from scripts/php-serialize/cases.php and from
https://github.com/$PHP_SRC_REPO commit $PHP_SRC_COMMIT
(string literals of .phpt tests and sapi/fuzzer/corpus/unserialize),
LICENSE is the license of php-src.  The expected results are the output of
PHP's unserialize() with allowed_classes => false.
EOS

echo "Updated $DATA"
