[package]
name = "csv"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-csv = { path = "../../deser-csv" }
deser-path = { path = "../../deser-path" }

[[bin]]
name = "csv"
path = "src/main.rs"
test = false
doc = false
