[package]
name = "deser-debug"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
version = "0.10.0"
edition.workspace = true
rust-version.workspace = true
description = "Debug formatting for values that implement Serialize of deser"
repository = "https://github.com/mitsuhiko/deser"
keywords = ["serialization", "debug", "formatting"]
categories = ["encoding", "value-formatting", "development-tools::debugging", "no-std"]
readme = "README.md"
license = "Apache-2.0"
documentation = "https://docs.rs/deser-debug"

[dependencies]
deser-core = { version = "0.10.0", path = "../deser-core", default-features = false }
[dev-dependencies]
deser = { version = "0.10.0", path = "../deser", features = ["derive"] }
