[package]
name = "deser-version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
deser = { path = "../../deser", features = ["derive"] }
deser-json = { path = "../../deser-json" }
